### ISSUE TITLE
[BUG] - GH-Pages Deployment

### ISSUE THREAD

**Issue by harshau007** [tcet-opensource/gdsc-website#3]
### Describe the bug

When we try to deploy our project to GitHub Pages it renders README.md file instead of static files

### Actual behavior

Should Deploy static files on GitHub pages

### Expected behavior

Deploys README.md file to GitHub Pages

### How to Reproduce?

1. Fork Repo
2. Enable GH pages from action via Settings
3. Run Action
4. Check GH page url

### Screenshots

N/A

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by vish-rt** [comment]
Would you like to work on this issue?

**Comment by harshau007** [comment]
Yes, I would like to work on this issue!!

**Comment by vish-rt** [comment]
Feel free to follow our [External Workflow](https://opensource.tcetmumbai.in/docs/resources/workflows/external-workflow/) and create a pull request to the `main` branch.

**Comment by harshau007** [comment]
Okk

**Comment by vish-rt** [comment]
Done!
