### ISSUE TITLE
[BUG] - The GDSC logo in the mobile view is not centered

### ISSUE THREAD

**Issue by 0amirk** [tcet-opensource/gdsc-website#6]
#### The logo that is present in the footer is not centered in the mobile view of the site. 

![Screenshot 2023-10-02 105547](https://github.com/tcet-opensource/gdsc-website/assets/133527168/a498a94f-8e84-4c1f-90f3-87b8e8e57a1f)

### Actual behavior

The mobile view logo's div is not centered relative to the page. 

### Expected behavior

The logo is expected to be in the center like the other content of the footer in mobile view.

### Steps to reproduce.

1. Visit the deployed site.
2. Right click and select inspect.
3. Adjust the size of the window to switch to mobile view.
4. Scroll down to the bottom for the footer.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by 0amirk** [comment]
Can i work on this issue ?

**Comment by vish-rt** [comment]
Feel free to follow our [External Workflow](https://opensource.tcetmumbai.in/docs/resources/workflows/external-workflow/) and create a pull request to the `main` branch.

**Comment by vish-rt** [comment]
Resolved
